---
- name: Restart Dock
  ansible.builtin.command: killall Dock
  changed_when: true
  listen: restart dock

- name: Restart Finder
  ansible.builtin.command: killall Finder
  changed_when: true
  listen: restart finder
