---
- name: Ensure ~/.local/bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.local/bin"
    state: directory
    mode: "0755"
  tags:
    - scripts

- name: Install synology-cloudsync-decrypt script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/laptop/files/scripts/synology-cloudsync-decrypt.py"
    dest: "{{ ansible_facts.env.HOME }}/.local/bin/synology-cloudsync-decrypt"
    mode: "0755"
  tags:
    - scripts
